site_name: My Docs
theme:
  name: material
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - markdown_captions
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
