site_name: My Docs
theme:
  name: material
  logo: fontawesome/solid/hat-cowboy
  features:
  - content.code.copy
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - markdown_captions
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
