name: HW1 Autograder

on:
  push:
    branches:
      - hw1

jobs:
  setup:
    name: Set up environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Problem 1
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/wustl-data/hw1
          push: never
          runCmd: poetry run pytest tests/test_autograde.py::test_1_uses_sql
      - name: Problem 2
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/wustl-data/hw1
          push: never
          runCmd: poetry run pytest tests/test_autograde.py::test_2_uses_pandas
