name: HW1 Autograder

on:
  push:
    branches:
      - main
    tags:
      - 1.*.*

jobs:
  autograder:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Run local tests
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/wustl-data/dev:latest
          push: never
          runCmd: poetry run pytest
      - name: Run hidden tests
        run: docker run --rm ghcr.io/wustl-data/fl23-autograder:main pytest
