name: HW1 Autograder

on: workflow_dispatch

jobs:
  p1_dev:
    name: Run pytest in autograder
    uses: devcontainers/ci@v0.3
    with:
      # [Optional] If you have a separate workflow like the one above
      # to pre-build your container image, you can reference it here
      # to speed up your application build workflows as well!
      cacheFrom: ghcr.io/example/example-devcontainer

      push: never
      runCmd: pytest
  p1:
    name: Problem 1
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wustl-data/autograder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Does filter_after_cutoff_age use SQL?
        run: pytest tests/local/test_autograde.py::test_1_uses_sql

  p2:
    name: Problem 2
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wustl-data/autograder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Does avg_per_state avoid using SQL?
        run: pytest tests/local/test_autograde.py::test_2_uses_pandas

  p3:
    name: Problem 3
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wustl-data/autograder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Does your test cover all example cases?
        run: docker run -w /workspaces/autograder -v .:/workspaces/autograder ghcr.io/wustl-data/autograder pytest /workspaces/autograder/tests/hidden/test_action.py::test_autograder_parge_states_adult_age
  p4:
    name: Problem 4
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wustl-data/autograder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Does your implementation get your test to pass?
        run: pytest tests/local/test_hw1.py::test_large_states_adult_age
  p5:
    name: Problem 5
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wustl-data/autograder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Does your implementation get your test to pass?
        run: pytest tests/local/test_hw1.py::test_large_states_adult_age
  p6:
    name: Problem 6
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wustl-data/autograder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Does your implementation get your test to pass?
        run: pytest tests/local/test_hw1.py::test_large_states_adult_age
  p7:
    name: Problem 7
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wustl-data/autograder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Does your implementation get your test to pass?
        run: pytest tests/local/test_hw1.py::test_large_states_adult_age

      - name: Does your test cover all example cases?
        run: docker run -w /workspaces/autograder -v .:/workspaces/autograder ghcr.io/wustl-data/autograder pytest /workspaces/autograder/tests/hidden/test_action.py::test_autograder_generate_people
  p8:
    name: Problem 8
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wustl-data/autograder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Does your implementation get your test to pass?
        run: pytest tests/local/test_hw1.py::test_generate_people.py
