name: Test run of autograder for pre-release

on:
  push:
    branches:
      - hw1-prerelease

jobs:
  autograder:
    name: Autograder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build image and run autograder
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/wustl-data/hw1
          cacheFrom: ghcr.io/example/hw1
          push: always
          runCmd: pytest
